In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = [
    'The glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of work',
    'I enjoy machine learning'
]

In [3]:
sent

['The glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of work',
 'I enjoy machine learning']

In [4]:
# Vocabulary size
voc_size = 10000

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent ]
print(onehot_repr)

[[3358, 9713, 1234, 1399], [3358, 9713, 1234, 1552], [3358, 9798, 1234, 2516], [4202, 3494, 3577, 7121, 9095], [4202, 3494, 3577, 7121, 2368], [4590, 3358, 9392, 1234, 4177], [4202, 3621, 127, 6969]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 3358 9713 1234 1399]
 [   0    0    0    0 3358 9713 1234 1552]
 [   0    0    0    0 3358 9798 1234 2516]
 [   0    0    0 4202 3494 3577 7121 9095]
 [   0    0    0 4202 3494 3577 7121 2368]
 [   0    0    0 4590 3358 9392 1234 4177]
 [   0    0    0    0 4202 3621  127 6969]]


In [12]:
dim = 15

In [14]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile(
    'adam',
    'mse'
)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 15)             150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 122ms/step
[[[ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.01673684 -0.00177007  0.02718082  0.04202176 -0.0098138
   -0.0070164  -0.03087561 -0.04081458 -0.03848165 -0.02807623
    0.01956627  0.03263093 -0.04337031 -0.00211285 -0.02429764

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3358, 9713, 1234, 1399], dtype=int32)

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 21ms/step
[[[ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.02599335  0.00618414  0.008482    0.03708061 -0.00436823
   -0.00308346 -0.0209124  -0.00521743  0.04980001 -0.04160001
    0.02080167  0.01893998 -0.03777506  0.03364365  0.04017987]
  [ 0.01673684 -0.00177007  0.02718082  0.04202176 -0.0098138
   -0.0070164  -0.03087561 -0.04081458 -0.03848165 -0.02807623
    0.01956627  0.03263093 -0.04337031 -0.00211285 -0.02429764]